spring:
  application:
    name: streamsheet-demo

streamsheet:
  row-access-window-size: 100
  flush-batch-size: 1000
  compress-temp-files: true
  storage:
    type: LOCAL
    local:
      path: build/exports
      base-url: http://localhost:8080/api/streamsheet/download

logging:
  level:
    com.streamsheet: DEBUG
